### ISSUE TITLE
ResizeObserver is not polyfilled even though `|force` is used

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#10]
This is my current script tag:

```html
<script crossorigin src="https://polyfill.app/api/polyfill?features=es,fetch,pointer-event,scroll-behavior,resize-observer|force"></script>
```

An hour ago I got this error on Sentry:

<img width="746" alt="Screen Shot 2020-03-05 at 9 27 53 AM" src="https://user-images.githubusercontent.com/331833/76007880-99c9e300-5ec3-11ea-8497-8eb8516cfcf5.png">

For some reason `ResizeObserver` is not being polyfilled.

This is the user agent:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1
```

<img width="905" alt="Screen Shot 2020-03-05 at 9 28 24 AM" src="https://user-images.githubusercontent.com/331833/76007958-b8c87500-5ec3-11ea-8030-df06d014c610.png">

**Comment by wessberg** [comment]
Hey there. I'm wondering if this could be related your index.html file being cached by the device that visited your site? And thereby also pointing to a cached version of the polyfill bundle, before you added the `force` option to `resize-observer`. iOS Safari can sometimes be extremely tricky to cache-bust, particularly when filenames remain the same across deployments such as `index.html` usually does 

The `force` option always include the feature. Opening [this link](https://polyfill.app/api/polyfill?features=resize-observer|force) will include the `resize-observer` polyfill in any browser.

**Comment by tommedema** [comment]
@wessberg nope, after your suggestion I looked this same user + session up in full story where I verified the network log:

<img width="1493" alt="Screen Shot 2020-03-05 at 12 18 30 PM" src="https://user-images.githubusercontent.com/331833/76022159-727f1000-5edb-11ea-87c9-4711ed5eb354.png">

I can guarantee that it was loading this url:

```
https://polyfill.app/api/polyfill?features=es,fetch,pointer-event,scroll-behavior,resize-observer|force
```

**Comment by wessberg** [comment]
I've investigated the issue from an iOS 13.3 device, and the issue seems to be that the execution of the polyfill bundle fails at an earlier point:
<img width="1440" alt="Screen Shot 2020-03-06 at 11 37 10 AM" src="https://user-images.githubusercontent.com/20454213/76076535-5b095b00-5f9f-11ea-91e2-0ada73d7dc3a.png">

This means that it never gets beyond polyfilling missing EcmaScript language features (so neither ResizeObserver, PointerEvents, scroll-behavior, etc gets polyfilled).

You can safely remove the `force` option, because this issue is rather an issue with how the core-js modules are bundled together which I'll look into. It seems to be directly related to [this issue](https://github.com/wessberg/Polyfiller/issues/8), which also happens to be happening when evaluating core-js internals on Safari:

**Comment by tommedema** [comment]
@wessberg thank you; it's a little concerning that that issue is live since jan 10th. If I want to quickly workaround this, do you think temporarily removing `es` from the polyfills would avoid the core-js module bundling issue?

**Comment by wessberg** [comment]
I understand your situation. I've been looking into this a lot today and will continue to do so over the next hours since this causes a lot of issues right now. For now, you can try to leaving out `es`, yes. I will report back as soon as this has been resolved.

**Comment by wessberg** [comment]
I've fixed the issue remotely on the host. It was, as is often the case, related to a stale internal node_modules cache. Everything is fine now.

**Comment by tommedema** [comment]
Are you sure? Now I’m getting this

**Comment by wessberg** [comment]
There seems to be an issue with your comment. Is it missing an attachment or something like that?

**Comment by tommedema** [comment]
@wessberg Are you sure? Now I’m getting this

<img width="1225" alt="Screen Shot 2020-03-06 at 2 44 24 PM" src="https://user-images.githubusercontent.com/331833/76128378-070b7000-5fb9-11ea-8126-981e05226898.png">

<img width="636" alt="Screen Shot 2020-03-06 at 2 44 02 PM" src="https://user-images.githubusercontent.com/331833/76128386-0a066080-5fb9-11ea-90fa-23943e505e5f.png">

user agent:

```
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
```

**Comment by wessberg** [comment]
Yeah, I had to restart the process which meant that there were some downtime which led to polyfills not being served in that timeframe.

I just browsed your app from IE 11 on Windows 10 and it correctly polyfilled fetch:
<img width="1253" alt="Screen Shot 2020-03-06 at 11 53 13 PM" src="https://user-images.githubusercontent.com/20454213/76128861-d867b680-6005-11ea-9a23-cb51f16b58db.png">

I did loop into an error, though, unrelated to this, which might pop-up in your error tracker.

**Comment by tommedema** [comment]
Ok, I'll mark it as resolved.

For something like polyfill.app you'd probably want it to be highly available using AWS lambda etc
