### ISSUE TITLE
ES.string not polyfilled on QQ browser

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#14]
Browser:

<img width="907" alt="Screen Shot 2020-04-06 at 12 21 43 PM" src="https://user-images.githubusercontent.com/331833/78596834-4f5cbe80-7801-11ea-81cd-7e49a962cd6f.png">

User agent:

```

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 QBCore/4.0.1301.400 QQBrowser/9.0.2524.400 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2875.116 Safari/537.36 NetType/WIFI MicroMessenger/7.0.5 WindowsWechat
```

Error:

<img width="532" alt="Screen Shot 2020-04-06 at 12 21 52 PM" src="https://user-images.githubusercontent.com/331833/78596851-52f04580-7801-11ea-886c-4f05c117bc71.png">

Code:

```html
<script crossorigin src="https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior,es"></script>
```

It should polyfill es --> es.string --> padStart but it doesn't.

**Comment by wessberg** [comment]
Hey there. Thanks for reporting it. It has been fixed and deployed to production.
