### ISSUE TITLE
Production Regression --- Uncaught Error: Cannot find module '../internals/webkit-string-pad-bug'

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#18]
Creating a quick bug report because this just started appearing in production-

<img width="519" alt="Screen Shot 2020-07-02 at 7 01 04 PM" src="https://user-images.githubusercontent.com/331833/86424107-7444be80-bc96-11ea-899a-fc0a0b7b4529.png">

To be clear, we didn't change anything on our end.

This is our embed script:

```html
<script crossorigin src="https://polyfill.app/api/polyfill?features=fetch,pointer-event,scroll-behavior,es"></script>
```

**Comment by wessberg** [comment]
Sorry about that. This has been fixed now and is live.

**Comment by tommedema** [comment]
Thank you! Is there any way to prevent these things from spilling into
production?

**Comment by wessberg** [comment]
Well, having a staging environment would go a long way. In this particular case the tests are passing locally but Nanobox, which is a IaaS tool Polyfiller is hosted through, has a lot of caching problems. This is not the first time this breaks. In fact, I manually have to patch files in the running Docker container for each release to invalidate their cache. I think the best course of action is to migrate away from Nanobox as soon as possible, which - by the way - seems to be completely dead after being acquired by DigitalOcean. I'm looking into it.

It is worth mentioning that self-hosting the Docker image doesn't have the same problems.
