### ISSUE TITLE
Downtime (again)

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#26]
<img width="851" alt="Screen Shot 2020-10-22 at 3 48 34 PM" src="https://user-images.githubusercontent.com/331833/96937904-0e1abc00-147e-11eb-9074-ad1d33a2c512.png">
<img width="235" alt="Screen Shot 2020-10-22 at 3 47 30 PM" src="https://user-images.githubusercontent.com/331833/96937917-1246d980-147e-11eb-8b96-e2ebe97e2c72.png">

@wessberg

**Comment by wessberg** [comment]
Whoops, sorry! I'm rolling out a major new update of Polyfiller right now that has been a long time underway. It is up again now.
I'll write some release notes that you can take a look at when it's done to see what's new.

**Comment by tommedema** [comment]
I see. For public facing services like yours, you might want to consider a green blue deployment process

**Comment by wessberg** [comment]
Something like that is actually what I just rolled out (along with other improvements to the core product). There's a staging environment now and rolling updates based on CI. Up until now, there were no such thing as a staging environment. Going forward, this will ensure much greater stability.
