### ISSUE TITLE
Error in Web Service API Reference

### ISSUE THREAD

**Issue by arodriguezpreference** [wessberg/Polyfiller#57]
Error in access to script:

https://polyfill.app/api/polyfill?features=broadcast-channel

502 Bad Gateway
------------------------
nginx/1.18.0 (Ubuntu)

**Comment by Vangelis66** [comment]
Will this be addressed somehow? It seems **every polyfill** served from `polyfill.app` now yields the same `502` **HTTP Error**...
FWIW, I'm requesting: 
```
https://polyfill.app/api/polyfill?minify&features=intl|locale=en~es~el
```

**Comment by wessberg** [comment]
Sorry about that. It seems I've missed this issue. The web service is live again.
