### ISSUE TITLE
Uint32Array Safari 9 El Capitain webpack console error

### ISSUE THREAD

**Issue by norgeous** [wessberg/Polyfiller#8]
Using:
* `<script crossorigin="anonymous" src="https://polyfill.app/api/polyfill?features=es"></script>`
* Browserstack: OSX El Capitan, Safari 9.1

I get the following error:
![image](https://user-images.githubusercontent.com/4681349/72164769-38532f80-33be-11ea-8ec7-31e3598ef2e3.png)

Involved 🤷‍♂:
* es.typed-array.uint32-array
* es.typed-array.from

**Comment by wessberg** [comment]
Hi there. Sorry for the late reply. This was related to issues with a stale node_modules cache on the remote host. It has since been fixed.
