### ISSUE TITLE
Resize observer is not polyfilled in FBAN (Facebook) browser

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#9]
User agent:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 LightSpeed [FBAN/MessengerLiteForiOS;FBAV/253.1.0.43.116;FBBV/200174216;FBDV/iPhone11,6;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/3;FBCR/;FBID/phone;FBLC/en_US;FBOP/0]
```

This is a version of the Safari browser on iOS. For some reason the resize observer is not polyfilled even with this script tag:

```
<script crossorigin src="https://polyfill.app/api/polyfill?features=es,fetch,pointer-event,scroll-behavior,resize-observer"></script>
```

<img width="871" alt="Screen Shot 2020-02-27 at 4 17 34 PM" src="https://user-images.githubusercontent.com/331833/75498739-dbff9b80-597c-11ea-9c30-c3037bb5ffd1.png">

<img width="1199" alt="Screen Shot 2020-02-27 at 4 18 47 PM" src="https://user-images.githubusercontent.com/331833/75498742-df932280-597c-11ea-948b-1d123a2e96b0.png">

**Comment by wessberg** [comment]
Hey Tom. Thanks for reporting this issue! It has been fixed in [v.0.0.95](https://github.com/wessberg/Polyfiller/releases/tag/v0.0.95) and has gone live.

**Comment by tommedema** [comment]
@wessberg nice, thanks!

Can I now safely change:

```
<script crossorigin src="https://polyfill.app/api/polyfill?features=es,fetch,pointer-event,scroll-behavior,resize-observer|force"></script>
```

To:

```
<script crossorigin src="https://polyfill.app/api/polyfill?features=es,fetch,pointer-event,scroll-behavior,resize-observer"></script>
```

?

Curious what caused and solved the bug as I couldn't find a [relevant code change](https://github.com/wessberg/Polyfiller/compare/04c1103cf951994a13939c0e86f0b37dfa504b7f...master) in your recent commits?

**Comment by wessberg** [comment]
Yes, indeed you can. The bug needed to be fixed in [this package](https://github.com/wessberg/browserslist-generator/releases/tag/v1.0.34), which is a dependency of Polyfiller. You'll see that it was fixed by bumping the dependency.
